let dataInfoTablet = {"total" :21,
 "totalNotFiltered" : 21,
 "rows" : [
  {
   "id":0,
   "raiting": "<p class='aa-tablet__raiting'>★★★</p>",
   "name":"<a class='aa-tablet__link' href='./project.html'>RED7</a>",
   "customer": "АО 'ГК 'ОСНОВА'",
   "projector":"'ООО 'Спектрум -Холдинг'",
   "date": "12.12.12",
   "district": "ЦАО",
   "agr": "12.12.12",
   "archmain": "13.12.12",
   "tags": "высотное здание, архзначимый",
   "function": "жилое здание"
  },
  {
    "id":1,
    "raiting": "<p class='aa-tablet__raiting'>★★</p>",
    "name":"<a class='aa-tablet__link' href='./project.html'>музейный центр (структурное подразделение ФГБУК «Государственного исторического музея»)</a> ",
    "customer": "АО 'ГК 'ОСНОВА'",
    "projector": "MVRDV Проектное бюро АПЕКС",
    "date": "12.12.12",
    "district": "ЦАО",
    "agr": "12.12.12",
    "archmain": "18.01.12",
    "tags": "высотное здание, архзначимый",
    "function": "жилое здание"
   },
   {
    "id":2,
    "raiting": "<p class='aa-tablet__raiting'>★★★</p>",
    "name":"<a class='aa-tablet__link' href='./project.html'>ЖК «Павелецкая сити»</a>",
    "customer": "АО 'ГК 'ОСНОВА'",
    "projector": "Апекс, Wall, Меганом и др.",
    "date": "12.12.12",
    "district": "ЦАО",
    "agr": "12.12.12",
    "archmain": "15.10.12",
    "tags": "высотное здание, архзначимый",
    "function": "жилое здание"
   },
   {
    "id":3,
    "raiting": "<p class='aa-tablet__raiting'>★</p>",
    "name":"<a class='aa-tablet__link' href='./project.html'>ЖК High Life</a>",
    "customer": "АО 'ГК 'ОСНОВА'",
    "projector": "MVRDV Проектное бюро АПЕКС",
    "date": "12.12.12",
    "district": "ЦАО",
    "agr": "12.12.12",
    "archmain": "13.12.12",
    "tags": "высотное здание, архзначимый",
    "function": "жилое здание"
   },
   {
    "id":4,
    "raiting": "<p class='aa-tablet__raiting'>★★★</p>",
    "name":"<a class='aa-tablet__link' href='./project.html'>Северный речной порт</a>",
    "customer": "Мангазея Легенда",
    "projector": "Архитектурное бюро Сергея Скуратова",
    "date": "12.12.12",
    "district": "ЦАО",
    "agr": "12.12.12",
    "archmain": "13.12.12",
    "tags": "высотное здание, архзначимый",
    "function": "жильё, офисы, апартаменты, гостиницы, административные, торговые центры, общесвтенные центры"
   },
   {
    "id":5,
    "raiting": "<p class='aa-tablet__raiting'>★</p>",
    "name":"<a class='aa-tablet__link' href='./project.html'>Северный речной порт</a>",
    "customer": "Мангазея Легенда",
    "projector": "Архитектурное бюро Сергея Скуратова",
    "date": "12.12.12",
    "district": "ЦАО",
    "agr": "12.12.12",
    "archmain": "13.12.12",
    "tags": "высотное здание, архзначимый",
    "function": "жильё, офисы, апартаменты, гостиницы, административные, торговые центры, общесвтенные центры"
   },
   {
    "id":6,
    "raiting": "<p class='aa-tablet__raiting'>★</p>",
    "name":"<a class='aa-tablet__link' href='./project.html'>Северный речной порт</a>",
    "customer": "Мангазея Легенда",
    "projector": "Архитектурное бюро Сергея Скуратова",
    "date": "12.12.12",
    "district": "ЦАО",
    "agr": "12.12.12",
    "archmain": "13.12.12",
    "tags": "высотное здание, архзначимый",
    "function": "жильё, офисы, апартаменты, гостиницы, административные, торговые центры, общесвтенные центры"
   },
   {
    "id":7,
    "raiting": "<p class='aa-tablet__raiting'>★★★</p>",
    "name":"<a class='aa-tablet__link' href='./project.html'>Северный речной порт</a>",
    "customer": "Мангазея Легенда",
    "projector": "Архитектурное бюро Сергея Скуратова",
    "date": "12.12.12",
    "district": "ЦАО",
    "agr": "12.12.12",
    "archmain": "13.12.12",
    "tags": "высотное здание, архзначимый",
    "function": "жильё, офисы, апартаменты, гостиницы, административные, торговые центры, общесвтенные центры"
   },
   {
    "id":8,
    "raiting": "<p class='aa-tablet__raiting'>★★</p>",
    "name":"<a class='aa-tablet__link' href='./project.html'>Северный речной порт</a>",
    "customer": "Мангазея Легенда",
    "projector": "Медиа",
    "date": "12.12.12",
    "district": "ЦАО",
    "agr": "12.12.12",
    "archmain": "13.12.12",
    "tags": "высотное здание, архзначимый",
    "function": " торговые центры, общесвтенные центры"
   },
   {
    "id":9,
    "raiting": "<p class='aa-tablet__raiting'>★</p>",
    "name":"<a class='aa-tablet__link' href='./project.html'>Северный речной порт</a>",
    "customer": "Мангазея Легенда",
    "projector": "Бабушкин Локал",
    "date": "12.12.12",
    "district": "ЦАО",
    "agr": "12.12.12",
    "archmain": "13.12.12",
    "tags": "высотное здание, архзначимый",
    "function": "жильё, офисы, апартаменты, административные, торговые центры"
   },
   {
    "id":10,
    "raiting": "<p class='aa-tablet__raiting'>★★★</p>",
    "name":"<a class='aa-tablet__link' href='./project.html'>Северный речной порт</a>",
    "customer": "Мангазея Легенда",
    "projector": "Архитектурное бюро Сергея Скуратова",
    "date": "12.12.12",
    "district": "ЦАО",
    "agr": "12.12.12",
    "archmain": "13.12.12",
    "tags": "высотное здание, архзначимый",
    "function": "жильё, офисы, общесвтенные центры"
   },
   {
    "id":11,
    "raiting": "<p class='aa-tablet__raiting'>★★</p>",
    "name":"<a class='aa-tablet__link' href='./project.html'>Северный речной порт</a>",
    "customer": "Мангазея Легенда",
    "projector": "Архитектурное бюро Сергея Скуратова",
    "date": "12.12.12",
    "district": "ЦАО",
    "agr": "12.12.12",
    "archmain": "13.12.12",
    "tags": "архзначимый",
    "function": "жильё,  административные, торговые центры, общесвтенные центры"
   },
   {
    "id":12,
    "raiting": "<p class='aa-tablet__raiting'>★★</p>",
    "name":"<a class='aa-tablet__link' href='./project.html'>Северный речной порт</a>",
    "customer": "Мангазея Легенда",
    "projector": "Архитектурное бюро Сергея Скуратова",
    "date": "12.12.12",
    "district": "ЦАО",
    "agr": "12.12.12",
    "archmain": "13.12.12",
    "tags": "архзначимый",
    "function": "жильё,  административные, торговые центры, общесвтенные центры"
   },
   {
    "id":13,
    "raiting": "<p class='aa-tablet__raiting'>★★</p>",
    "name":"<a class='aa-tablet__link' href='./project.html'>Северный речной порт</a>",
    "customer": "Мангазея Легенда",
    "projector": "Архитектурное бюро Сергея Скуратова",
    "date": "12.12.12",
    "district": "ЦАО",
    "agr": "12.12.12",
    "archmain": "13.12.12",
    "tags": "архзначимый",
    "function": "жильё,  административные, торговые центры, общесвтенные центры"
   },
   {
    "id":14,
    "raiting": "<p class='aa-tablet__raiting'>★★</p>",
    "name":"<a class='aa-tablet__link' href='./project.html'>Северный речной порт</a>",
    "customer": "Мангазея Легенда",
    "projector": "Архитектурное бюро Сергея Скуратова",
    "date": "12.12.12",
    "district": "ЦАО",
    "agr": "12.12.12",
    "archmain": "13.12.12",
    "tags": "архзначимый",
    "function": "жильё,  административные, торговые центры, общесвтенные центры"
   },
   {
    "id":15,
    "raiting": "<p class='aa-tablet__raiting'>★★</p>",
    "name":"<a class='aa-tablet__link' href='./project.html'>Северный речной порт</a>",
    "customer": "Мангазея Легенда",
    "projector": "Архитектурное бюро Сергея Скуратова",
    "date": "12.12.12",
    "district": "ЦАО",
    "agr": "12.12.12",
    "archmain": "13.12.12",
    "tags": "архзначимый",
    "function": "жильё,  административные, торговые центры, общесвтенные центры"
   },
   {
    "id":16,
    "raiting": "<p class='aa-tablet__raiting'>★★</p>",
    "name":"<a class='aa-tablet__link' href='./project.html'>Северный речной порт</a>",
    "customer": "Мангазея Легенда",
    "projector": "Архитектурное бюро Сергея Скуратова",
    "date": "12.12.12",
    "district": "ЦАО",
    "agr": "12.12.12",
    "archmain": "13.12.12",
    "tags": "архзначимый",
    "function": "жильё,  административные, торговые центры, общесвтенные центры"
   },
   {
    "id":17,
    "raiting": "<p class='aa-tablet__raiting'>★★</p>",
    "name":"<a class='aa-tablet__link' href='./project.html'>Северный речной порт</a>",
    "customer": "Мангазея Легенда",
    "projector": "Архитектурное бюро Сергея Скуратова",
    "date": "12.12.12",
    "district": "ЦАО",
    "agr": "12.12.12",
    "archmain": "13.12.12",
    "tags": "архзначимый",
    "function": "жильё,  административные, торговые центры, общесвтенные центры"
   },
   {
    "id":18,
    "raiting": "<p class='aa-tablet__raiting'>★★</p>",
    "name":"<a class='aa-tablet__link' href='./project.html'>Северный речной порт</a>",
    "customer": "Мангазея Легенда",
    "projector": "Архитектурное бюро Сергея Скуратова",
    "date": "12.12.12",
    "district": "ЦАО",
    "agr": "12.12.12",
    "archmain": "13.12.12",
    "tags": "архзначимый",
    "function": "жильё,  административные, торговые центры, общесвтенные центры"
   },
   {
    "id":19,
    "raiting": "<p class='aa-tablet__raiting'>★★</p>",
    "name":"<a class='aa-tablet__link' href='./project.html'>Северный речной порт</a>",
    "customer": "Мангазея Легенда",
    "projector": "Архитектурное бюро Сергея Скуратова",
    "date": "12.12.12",
    "district": "ЦАО",
    "agr": "12.12.12",
    "archmain": "13.12.12",
    "tags": "архзначимый",
    "function": "жильё,  административные, торговые центры, общесвтенные центры"
   },
   {
    "id":20,
    "raiting": "<p class='aa-tablet__raiting'>★★</p>",
    "name":"<a class='aa-tablet__link' href='./project.html'>Северный речной порт</a>",
    "customer": "Мангазея Легенда",
    "projector": "Архитектурное бюро Сергея Скуратова",
    "date": "12.12.12",
    "district": "ЦАО",
    "agr": "12.12.12",
    "archmain": "13.12.12",
    "tags": "архзначимый",
    "function": "жильё,  административные, торговые центры, общесвтенные центры"
   }

  
]}


export default dataInfoTablet;